export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INGREDIENTS_LOADING_ERROR = 'INGREDIENTS_LOADING_ERROR';

export const ACCEPT_ORDER = 'ACCEPT_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const PURCHASING_ORDER = 'PURCHASING_ORDER';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const ORDERS_INIT = 'ORDERS_INIT';
export const ORDERS_DONE = 'ORDERS_DONE';
export const ORDERS_FAIL = 'ORDERS_FAIL';

export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_DONE = 'AUTH_DONE';
export const AUTH_FAIL = 'AUTH_FAIL';

