export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INGREDIENTS_LOADING_ERROR = 'INGREDIENTS_LOADING_ERROR';

export const ACCEPT_ORDER = 'ACCEPT_ORDER';
export const CANCEL_ORDER = 'CANCEL_ORDER';
export const PURCHASING_ORDER = 'PURCHASING_ORDER';
export const PURCHASE_INIT = 'PURCHASE_INIT';
